networks:
  42chan:
    name: 42chan
    driver: bridge


services:
  postgres:
    container_name: postgres
    image: postgres:18.4-alpine3.24
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_pwd
    secrets:
      - db_root_pwd
      - db_website_pwd
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - pgdata:/var/lib/postgresql
    networks:
      - 42chan
    ports:
      - 5432:5432

  nginx:
    container_name: nginx
    build: srcs/nginx/
    ports:
      - 443:443
    restart: unless-stopped
    environment:
      - ADDRESS=${ADDRESS}
    extra_hosts:
      - "host.parent:host-gateway"

  next:
    container_name: next
    build: srcs/next/
    restart: unless-stopped
    secrets:
      - db_website_pwd
    depends_on:
      - postgres
    profiles: ["prod"]

secrets:
  db_root_pwd:
    file: secrets/db_root_pwd.txt
  db_website_pwd:
    file : secrets/db_website_pwd.txt

volumes:
  pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/db