import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getSession } from "%/lib/auth"
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    const session = await getSession();
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} >
          <body>
              <header className="fixed top-0 h-16 w-full bg-beige flex items-center justify-center">
                <div>hello</div>
                <div className={"align-right"}>
                    {session ? (
                        <p>Connecté en tant que {session.user.username}</p>
                    ) : (
                        <a href="/auth/login">Se connecter</a>
                    )}
                </div>
              </header>
              <div className="min-h-full item-center flex flex-col">{children}</div>
              <footer className={"flex h-16 w-full bg-beige items-center justify-center"}>
                <p>Privacy Policy and Terms of Service</p>
              </footer>
            </body>
        </html>
      );
}
